# Use postgres/example user/password credentials
version: '3.7'

networks:
  javapost:
    name: custom_javapost

services:

  db:
    container_name: postgres
    image: postgres:12.2-alpine
    restart: always
    networks:
      - javapost
    environment:
      VOLUME: /srv/docker/postgres/data:/var/lib/postgresql/data
      POSTGRES_PASSWORD: PostGres2020!

  web:
    container_name: java
    image:  services
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - javapost
    expose:
      - 8000
    environment:
      url: jdbc:postgres://postgres:5432/wucashflow
      user: postgres
      password: PostGres2020!

